global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.yml"   # <-- nueva

scrape_configs:
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8001']
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

# (opcional) estado de la propia cola sin aÃ±adir servicios
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']   # metrics-plugin ya viene en la imagen 3.12-management
    metrics_path: /metrics